### ISSUE TITLE
Unexpected input(s) 'index-document', 'error-document', valid inputs are ['connection-string', 'folder', 'blob-container-name', 'public-access-policy', 'enabled-static-website']

### ISSUE THREAD

**Issue by ma3yta** [lauchacarro/Azure-Storage-Action#8]
``Unexpected input(s) 'index-document', 'error-document', valid inputs are ['connection-string', 'folder', 'blob-container-name', 'public-access-policy', 'enabled-static-website']``

```yaml
- name: Deploy to storage
      uses: lauchacarro/Azure-Storage-Action@v1.1
      with:
        enabled-static-website: 'true'
        folder: ${{ env.OUTPUT_PATH }}/webapp/wwwroot
        index-document: 'index.html'
        error-document: 'index.html' 
        connection-string: ${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}
```
